import { IntegrationPlatform, ApiKeyField } from './types';

export const ALL_PLATFORMS: IntegrationPlatform[] = [
  // ============================================
  // AD PLATFORMS
  // ============================================
  
  {
    id: 'metaAds',
    name: 'Meta Ads',
    description: 'Facebook and Instagram advertising platform for campaign management and analytics',
    icon: '📊',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect to manage your Meta advertising campaigns across Facebook and Instagram.',
  },
  {
    id: 'googleAds',
    name: 'Google Ads',
    description: 'Google\'s platform for search, display, and video advertising',
    icon: '🔍',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: true,
    setupInstructions: 'Sign in with your Google Ads account to sync campaign data.',
  },
  {
    id: 'googleAnalytics',
    name: 'Google Analytics',
    description: 'Tracks and reports website traffic and user behavior',
    icon: '📈',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Authorize access to your Google Analytics properties.',
  },
  {
    id: 'tiktokAds',
    name: 'TikTok Ads',
    description: 'Analytics for TikTok ad campaigns and audience engagement',
    icon: '🎬',
    iconColor: 'text-black',
    bgColor: 'bg-gray-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your TikTok Ads Manager account.',
  },
  {
    id: 'linkedinAds',
    name: 'LinkedIn Ads',
    description: 'B2B advertising on LinkedIn\'s professional network',
    icon: '💼',
    iconColor: 'text-blue-700',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your LinkedIn Campaign Manager account.',
  },
  {
    id: 'twitterAds',
    name: 'X Ads',
    description: 'Advertising platform for X (Twitter) to reach targeted audiences',
    icon: '🎯',
    iconColor: 'text-black',
    bgColor: 'bg-gray-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your X Ads account.',
  },
  {
    id: 'snapchatAds',
    name: 'Snapchat Ads',
    description: 'Mobile-first ad platform for Snapchat\'s audience',
    icon: '👻',
    iconColor: 'text-yellow-500',
    bgColor: 'bg-yellow-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Snapchat Ads account.',
  },
  {
    id: 'pinterestAds',
    name: 'Pinterest Ads',
    description: 'Visual discovery and shopping ads on Pinterest',
    icon: '📌',
    iconColor: 'text-red-600',
    bgColor: 'bg-red-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Pinterest Business account.',
  },
  {
    id: 'redditAds',
    name: 'Reddit Ads',
    description: 'Community-driven advertising on Reddit\'s platform',
    icon: '🤖',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Reddit Ads account.',
  },
  {
    id: 'amazonAds',
    name: 'Amazon Ads',
    description: 'Advertising solutions across Amazon\'s marketplace and media',
    icon: '📦',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Amazon Advertising account.',
  },
  {
    id: 'youtubeAds',
    name: 'YouTube Ads',
    description: 'Video advertising on YouTube, managed via Google Ads',
    icon: '▶️',
    iconColor: 'text-red-600',
    bgColor: 'bg-red-100',
    requiresOAuth: true,
    setupInstructions: 'Connect via Google Ads to manage YouTube advertising.',
  },

  // ============================================
  // ANALYTICS TOOLS
  // ============================================
  
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product and user analytics for web and mobile apps',
    icon: '📊',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'projectId',
        label: 'Project ID',
        type: 'text',
        placeholder: 'Your Mixpanel project ID',
        required: true,
      },
      {
        name: 'apiSecret',
        label: 'API Secret',
        type: 'password',
        placeholder: 'Your API secret',
        required: true,
      },
    ],
    setupInstructions: 'Get credentials from Mixpanel Project Settings.',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Product analytics for user behavior and retention',
    icon: '📈',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Amplitude API key',
        required: true,
      },
      {
        name: 'secretKey',
        label: 'Secret Key',
        type: 'password',
        placeholder: 'Your Amplitude secret key',
        required: true,
      },
    ],
    setupInstructions: 'Find keys in Amplitude Settings > Projects.',
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    description: 'Heatmaps, session recordings, and user feedback for websites',
    icon: '🔥',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'siteId',
        label: 'Site ID',
        type: 'text',
        placeholder: 'Your Hotjar Site ID',
        required: true,
      },
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Hotjar API key',
        required: true,
      },
    ],
    setupInstructions: 'Get your Site ID and API key from Hotjar Settings.',
  },
  {
    id: 'heap',
    name: 'Heap Analytics',
    description: 'Automatic event tracking and analytics for digital products',
    icon: '🔄',
    iconColor: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'appId',
        label: 'App ID',
        type: 'text',
        placeholder: 'Your Heap App ID',
        required: true,
      },
    ],
    setupInstructions: 'Find your App ID in Heap Account > Install.',
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Customer data platform for collecting and routing analytics data',
    icon: '🔀',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'writeKey',
        label: 'Write Key',
        type: 'password',
        placeholder: 'Your Segment write key',
        required: true,
      },
    ],
    setupInstructions: 'Find your Write Key in Segment Sources > Settings.',
  },
  {
    id: 'adobeAnalytics',
    name: 'Adobe Analytics',
    description: 'Enterprise-level web analytics and reporting',
    icon: '📊',
    iconColor: 'text-red-600',
    bgColor: 'bg-red-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'companyId',
        label: 'Company ID',
        type: 'text',
        placeholder: 'Your Adobe company ID',
        required: true,
      },
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'text',
        placeholder: 'Your client ID',
        required: true,
      },
      {
        name: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        placeholder: 'Your client secret',
        required: true,
      },
    ],
    setupInstructions: 'Get credentials from Adobe Experience Cloud.',
  },

  // ============================================
  // EMAIL MARKETING & AUTOMATION
  // ============================================
  
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing and automation platform with campaign analytics',
    icon: '🐵',
    iconColor: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Mailchimp account to sync your audiences.',
  },
  {
    id: 'activeCampaign',
    name: 'ActiveCampaign',
    description: 'Email marketing, automation, and CRM platform',
    icon: '🚀',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiUrl',
        label: 'API URL',
        type: 'text',
        placeholder: 'https://youraccountname.api-us1.com',
        required: true,
      },
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your API key',
        required: true,
      },
    ],
    setupInstructions: 'Get your API URL and key from Settings > Developer.',
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Cloud-based email delivery and marketing service',
    icon: '📧',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'SG.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
    setupInstructions: 'Generate an API key from SendGrid Settings > API Keys.',
  },
  {
    id: 'constantContact',
    name: 'Constant Contact',
    description: 'Email marketing and online marketing tools for SMBs',
    icon: '✉️',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Constant Contact account.',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'Email and SMS marketing for e-commerce brands',
    icon: '📨',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'privateKey',
        label: 'Private API Key',
        type: 'password',
        placeholder: 'pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
    setupInstructions: 'Find your Private API Key in Klaviyo Account > Settings > API Keys.',
  },
  {
    id: 'campaignMonitor',
    name: 'Campaign Monitor',
    description: 'Email marketing and automation for businesses',
    icon: '📮',
    iconColor: 'text-pink-600',
    bgColor: 'bg-pink-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Campaign Monitor API key',
        required: true,
      },
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'text',
        placeholder: 'Your client ID',
        required: true,
      },
    ],
    setupInstructions: 'Get API key from Account Settings > API keys.',
  },
  {
    id: 'drip',
    name: 'Drip',
    description: 'E-commerce marketing automation for email and SMS',
    icon: '💧',
    iconColor: 'text-blue-500',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Drip account for e-commerce automation.',
  },
  {
    id: 'brevo',
    name: 'Brevo (Sendinblue)',
    description: 'Email marketing and automation platform',
    icon: '✉️',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'xkeysib-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
    setupInstructions: 'Generate API key from Brevo Account > SMTP & API > API Keys.',
  },

  // ============================================
  // CRM & SALES PLATFORMS
  // ============================================
  
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Leading cloud-based CRM for sales, service, and marketing',
    icon: '☁️',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Salesforce organization.',
  },
  {
    id: 'zohoCRM',
    name: 'Zoho CRM',
    description: 'CRM platform for sales automation and pipeline management',
    icon: '📋',
    iconColor: 'text-red-600',
    bgColor: 'bg-red-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Zoho CRM account.',
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales CRM and pipeline management tool',
    icon: '🎯',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiToken',
        label: 'API Token',
        type: 'password',
        placeholder: 'Your Pipedrive API token',
        required: true,
      },
      {
        name: 'companyDomain',
        label: 'Company Domain',
        type: 'text',
        placeholder: 'yourcompany.pipedrive.com',
        required: true,
      },
    ],
    setupInstructions: 'Get your API token from Settings > Personal > API.',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing, sales, and service platform',
    icon: '🔶',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Authorize access to your HubSpot account.',
  },
  {
    id: 'dynamics365',
    name: 'Microsoft Dynamics 365',
    description: 'CRM and ERP applications for business management',
    icon: '🔷',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Dynamics 365 environment.',
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    description: 'CRM for sales automation and lead management',
    icon: '🌿',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'domain',
        label: 'Domain',
        type: 'text',
        placeholder: 'yourcompany.freshsales.io',
        required: true,
      },
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Freshsales API key',
        required: true,
      },
    ],
    setupInstructions: 'Get API key from Settings > API Settings.',
  },

  // ============================================
  // E-COMMERCE PLATFORMS
  // ============================================
  
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform for online stores and retail POS',
    icon: '🛍️',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'storeName',
        label: 'Store Name',
        type: 'text',
        placeholder: 'yourstore.myshopify.com',
        required: true,
      },
      {
        name: 'accessToken',
        label: 'Admin API Access Token',
        type: 'password',
        placeholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
    setupInstructions: 'Create a private app in Shopify Admin > Apps > Develop apps.',
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    description: 'WordPress plugin for customizable e-commerce stores',
    icon: '🛒',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'storeUrl',
        label: 'Store URL',
        type: 'text',
        placeholder: 'https://yourstore.com',
        required: true,
      },
      {
        name: 'consumerKey',
        label: 'Consumer Key',
        type: 'text',
        placeholder: 'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'consumerSecret',
        label: 'Consumer Secret',
        type: 'password',
        placeholder: 'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
    setupInstructions: 'Generate API keys in WooCommerce > Settings > Advanced > REST API.',
  },
  {
    id: 'magento',
    name: 'Magento',
    description: 'Open-source e-commerce platform by Adobe',
    icon: '🏪',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Magento store via OAuth.',
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    description: 'SaaS e-commerce platform for fast-growing brands',
    icon: '🏬',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your BigCommerce store.',
  },
  {
    id: 'wixEcommerce',
    name: 'Wix eCommerce',
    description: 'Website builder with integrated e-commerce features',
    icon: '🌐',
    iconColor: 'text-black',
    bgColor: 'bg-gray-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Wix store.',
  },

  // ============================================
  // SOCIAL MEDIA MANAGEMENT & LISTENING
  // ============================================
  
  {
    id: 'hootsuite',
    name: 'Hootsuite',
    description: 'Social media management and scheduling platform',
    icon: '🦉',
    iconColor: 'text-gray-700',
    bgColor: 'bg-gray-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Hootsuite account to manage social media.',
  },
  {
    id: 'sproutSocial',
    name: 'Sprout Social',
    description: 'Social media management, analytics, and engagement',
    icon: '🌱',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Sprout Social account.',
  },
  {
    id: 'buffer',
    name: 'Buffer',
    description: 'Social media scheduling and analytics tool',
    icon: '📅',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Buffer account.',
  },
  {
    id: 'brandwatch',
    name: 'Brandwatch',
    description: 'Social listening and analytics for brands',
    icon: '👁️',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Brandwatch API key',
        required: true,
      },
      {
        name: 'projectId',
        label: 'Project ID',
        type: 'text',
        placeholder: 'Your project ID',
        required: true,
      },
    ],
    setupInstructions: 'Get API credentials from Brandwatch admin panel.',
  },
  {
    id: 'mention',
    name: 'Mention',
    description: 'Real-time media monitoring and social listening',
    icon: '📣',
    iconColor: 'text-blue-500',
    bgColor: 'bg-blue-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'accessToken',
        label: 'Access Token',
        type: 'password',
        placeholder: 'Your Mention access token',
        required: true,
      },
      {
        name: 'accountId',
        label: 'Account ID',
        type: 'text',
        placeholder: 'Your account ID',
        required: true,
      },
    ],
    setupInstructions: 'Get access token from Mention API settings.',
  },

  // ============================================
  // CUSTOMER SUPPORT & ENGAGEMENT
  // ============================================
  
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Customer service and engagement platform',
    icon: '🎧',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Zendesk account.',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Conversational support and customer messaging',
    icon: '💬',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your Intercom workspace.',
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    description: 'Omnichannel customer support software',
    icon: '🌟',
    iconColor: 'text-green-600',
    bgColor: 'bg-green-100',
    requiresOAuth: false,
    requiresApiKey: true,
    apiKeyFields: [
      {
        name: 'domain',
        label: 'Domain',
        type: 'text',
        placeholder: 'yourcompany.freshdesk.com',
        required: true,
      },
      {
        name: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Your Freshdesk API key',
        required: true,
      },
    ],
    setupInstructions: 'Get API key from Profile Settings > API key.',
  },
  {
    id: 'liveChat',
    name: 'LiveChat',
    description: 'Live chat and help desk software for customer support',
    icon: '💭',
    iconColor: 'text-orange-600',
    bgColor: 'bg-orange-100',
    requiresOAuth: true,
    setupInstructions: 'Connect your LiveChat account.',
  },
];